# Generated by Django 4.2.7 on 2023-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotCatalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_slot', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('url_slot', models.URLField()),
                ('iframe_game_url', models.URLField()),
                ('provider', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('wide_release_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('game_type', models.CharField(max_length=255)),
                ('rtp', models.FloatField()),
                ('volatility', models.CharField(max_length=255)),
                ('hit_frequency', models.FloatField()),
                ('max_win', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('layout', models.CharField(max_length=255)),
                ('betways', models.FloatField()),
                ('features', models.TextField()),
                ('theme', models.CharField(max_length=255)),
                ('objects_slot', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('other_tags', models.CharField(max_length=255)),
                ('technology', models.CharField(max_length=255)),
                ('game_size', models.FloatField()),
                ('last_update', models.DateField()),
                ('blog_articles', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
