# Generated by Django 4.2.7 on 2023-11-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='game_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='game_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='hit_frequency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='iframe_game_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='layout',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='max_bet',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='max_win',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='min_bet',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='objects_slot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='other_tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='provider',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='rtp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='technology',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='theme',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='volatility',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='wide_release_date',
            field=models.DateField(null=True),
        ),
    ]
