# Generated by Django 4.2.7 on 2023-11-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_alter_slotcatalog_game_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
