# Generated by Django 4.2.7 on 2023-11-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_alter_slotcatalog_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='features',
            field=models.TextField(null=True),
        ),
    ]
