# Generated by Django 4.2.7 on 2023-11-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0004_alter_slotcatalog_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='betways',
            field=models.FloatField(null=True),
        ),
    ]
