# Generated by Django 4.2.7 on 2023-11-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0005_alter_slotcatalog_betways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='max_win',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
