# Generated by Django 4.2.7 on 2023-11-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0006_alter_slotcatalog_max_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='max_bet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='max_win',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='slotcatalog',
            name='min_bet',
            field=models.FloatField(null=True),
        ),
    ]
