# Generated by Django 4.2.7 on 2023-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0007_alter_slotcatalog_max_bet_alter_slotcatalog_max_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
