# Generated by Django 4.2.7 on 2023-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0008_alter_slotcatalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='iframe_game_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
