# Generated by Django 4.2.7 on 2023-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0009_alter_slotcatalog_iframe_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcatalog',
            name='iframe_game_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
